name: symplified-mutable-ci

on:
  # only trigger by hand
  workflow_dispatch:
    inputs:
      stage:
        description: 'all / build / test / coverage / docs'
        required: true
        default: all
        type: choice
        options: [all, build, test, coverage, docs]

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}

      # --- LLVM + Clang-18 ---
      - name: Install clang-18
        run: |
          wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s -- 18

      # --- system packages ---
      - run: sudo apt-get update &&
             sudo apt-get install -y ninja-build libboost-dev libtbb-dev libfmt-dev

      # --- version header generation by myself ---
      - run: echo '"dev-ci-build"' > include/mutable/gitversion.tbl

      # --- Configure & Build ---
      - name: Configure + Build
        env:
          CC:  clang
          CXX: clang++
        run: |
          export PATH=/usr/lib/llvm-18/bin:$PATH
          cmake -S . -B build -G Ninja \
                -DCMAKE_BUILD_TYPE=RelWithDebInfo \
                -DWITH_V8=OFF \
                -DMUTABLE_USE_SYSTEM_BOOST=ON \
                -DENABLE_SANITIZERS=OFF
          cmake --build build -j$(nproc)
  
      - uses: actions/upload-artifact@v4
        with:
          name: mutable-build
          path: build

  # ---------------------------------------
  test:
    if: github.actor == github.repository_owner && (inputs.stage == 'all' || inputs.stage == 'test')
    needs: build
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/download-artifact@v4
        with: { name: mutable-build, path: build }
      - name: Run unit tests
        run: ctest --test-dir build --output-on-failure

  # ---------------------------------------
  coverage:
    if: github.actor == github.repository_owner && (inputs.stage == 'all' || inputs.stage == 'coverage')
    needs: build
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/download-artifact@v4
        with: { name: mutable-build, path: build }
      - name: Run tests w/ coverage
        run: |
          cmake --build build --target coverage
          lcov --remove build/coverage.info '/usr/*' -o coverage.info
      - name: Upload LCOV report
        uses: codecov/codecov-action@v4
        with:
          files: coverage.info
